### ISSUE TITLE
Traceback on "classements" page.

### ISSUE THREAD

**Issue by jibo78** [dmartin35/pronosfoot#16]
Traceback on "classements" page at the end of the season.
One of the participants didn't validate the annual forecasts, perhaps that's what caused the crash?

```
<html><body>
<!--StartFragment--><h1>OperationalError
       at /classements/</h1>
  <pre class="exception_value">near "ISNULL": syntax error</pre>
  
Request Method: | GET
-- | --
https://pronos.domain.ovh/classements/
3.2.20
OperationalError
near "ISNULL": syntax error
/home/jay/.python/venv/pronosfoot/lib/python3.10/site-packages/django/db/backends/sqlite3/base.py, line 421, in execute
/home/jay/.python/venv/pronosfoot/bin/python3
3.10.12
['/home/jay/pronosfoot',  '/usr/lib/python310.zip',  '/usr/lib/python3.10',  '/usr/lib/python3.10/lib-dynload',  '/home/jay/.python/venv/pronosfoot/lib/python3.10/site-packages']
Tue, 21 May 2024 17:22:05 +0200

<!--EndFragment-->
</body>
</html>
```

```
Environment:


Request Method: GET
Request URL: https://pronos.domain.ovh/classements/

Django Version: 3.2.20
Python Version: 3.10.12
Installed Applications:
['django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.humanize',
 'django_js_reverse',
 'season',
 'admin',
 'memoize',
 'sslserver']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.locale.LocaleMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']
```

```
Traceback (most recent call last):
  File "/home/jay/.python/venv/pronosfoot/lib/python3.10/site-packages/django/db/backends/utils.py", line 82, in _execute
    return self.cursor.execute(sql)
  File "/home/jay/.python/venv/pronosfoot/lib/python3.10/site-packages/django/db/backends/sqlite3/base.py", line 421, in execute
    return Database.Cursor.execute(self, query)

The above exception (near "ISNULL": syntax error) was the direct cause of the following exception:
  File "/home/jay/.python/venv/pronosfoot/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/jay/.python/venv/pronosfoot/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/jay/pronosfoot/season/views.py", line 411, in tables
    'players_table':full_players_table_until_auto() if not eos else full_players_table_with_bonus(),
  File "/home/jay/pronosfoot/season/core/tables.py", line 143, in full_players_table_with_bonus
    user_table_bonus = [list(x) for x in user_table_with_bonus()]
  File "/home/jay/pronosfoot/season/queries.py", line 479, in user_table_with_bonus
    return executeRawSqlQuery(request)
  File "/home/jay/pronosfoot/tools/djangodb.py", line 13, in executeRawSqlQuery
    cursor.execute(query)
  File "/home/jay/.python/venv/pronosfoot/lib/python3.10/site-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
  File "/home/jay/.python/venv/pronosfoot/lib/python3.10/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/jay/.python/venv/pronosfoot/lib/python3.10/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/jay/.python/venv/pronosfoot/lib/python3.10/site-packages/django/db/backends/utils.py", line 79, in _execute
    with self.db.wrap_database_errors:
  File "/home/jay/.python/venv/pronosfoot/lib/python3.10/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/jay/.python/venv/pronosfoot/lib/python3.10/site-packages/django/db/backends/utils.py", line 82, in _execute
    return self.cursor.execute(sql)
  File "/home/jay/.python/venv/pronosfoot/lib/python3.10/site-packages/django/db/backends/sqlite3/base.py", line 421, in execute
    return Database.Cursor.execute(self, query)

Exception Type: OperationalError at /classements/
Exception Value: near "ISNULL": syntax error
```

**Comment by dmartin35** [comment]
the "ISNULL" is a mysql-only function, it's not supported by sqlite, neither postgresql.
i'll amend to make it compliant with all thoses databases, by refactoring the with/out bonus condition

**Comment by jibo78** [comment]
I can confirm that the fix is efficient. Many thanks!
